### ISSUE TITLE
ENV Credentials 

### ISSUE THREAD

**Issue by RichieMcMullen** [KaiBotan/strava-login#1]
I've had to edit the main class file with my api credentials. Your env placeholders are missing.

**Comment by kjellknapen** [comment]
I'm sorry about that, I forgot to add some part of code to my readme. You need to add this to your services config and then everything should work

'strava' => [
        'model' => App\User::class,
        'client_id' => env('STRAVA_KEY'),
        'client_secret' => env('STRAVA_SECRET'),
        'redirect_uri' => env('STRAVA_REDIRECT_URI'),
 ],

Hooe this helps :)

**Comment by RichieMcMullen** [comment]
That's no problem mate. I've added that but its still not working as expected. I see in your ServiceProvider you have `config('services.strava.client_id')` which looks correct, but for some reason its returning a `Bad Request` on the `client_id` field.

**Comment by RichieMcMullen** [comment]
Needed to clear the cache. Working fine now. Thanks alot mate.

**Comment by kjellknapen** [comment]
No problem! Thanks for bringing it to my attention. I'll make sure to add the line of code to my readme so that it won't happen again.

**Comment by RichieMcMullen** [comment]
Your welcome. Thank you for the package, its brilliant!
